name: comment gif
on:
  pull_request:
    paths:
      - vhs.tape
jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: charmbracelet/vhs-action@v1
        with:
          path: 'vhs.tape'
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./test_uname.gif
